siteTitle = "Alvis Ng"
siteDescr = "Father & Co-founder of Expade"
siteAuthor = "Alvis Ng"

siteTelegramUrl = "#"
siteFacebookUrl = "https://www.facebook.com/alvisng.me"
siteTwitterUrl = "https://twitter.com/alvis_bp"
siteGithubUrl = "#"
siteEmailUrl = "alvis.bpng@gmail.com"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = "UA-89161767-1"

linkPrefix = "/gatsby-starter-lumen"
